install.packages("ggplot2")
install.packages("magrittr")
install.packages("dplyr")
install.packages("wordcloud")
install.packages("tm")
install.packages("png")
install.packages("data.table")
install.packages("reshape2")
install.packages("igraph")
install.packages("scales")
install.packages("lda")
install.packages("LDAvis")
install.packages("topicmodels")
install.packages("rJava")
install.packages("openNLP")
install.packages("RColorBrewer")
require(devtools)
install_version("quanteda", version = "1.3.4", repos='http://cran.us.r-project.org', dependencies=TRUE)
